### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Roby1164** [CiFru/AdditionalBlocks#2]
This is the file with Italian language, you can add it, thanks.
delete for update

**Comment by CiFru** [comment]
Thanks! Will be added in the next update.

**Comment by Roby1164** [comment]
Apart from that, it should be updated, given that you have inserted new entries, in the last update you made, while I'm having problems with the other mod, that of verticals, which does not take the translation, even if I insert it in the file.

**Comment by Roby1164** [comment]
Use this I'm done updating it
[it_it.zip](https://github.com/CiFru/AdditionalBlocksStoneEdition/files/11959710/it_it.zip)

**Comment by CiFru** [comment]
Your translations have been added in the latest update (2.1.3), which has just dropped! Please let me know if there are any problems regarding the translations.

**Comment by Roby1164** [comment]
All ok. 
Now I wait for the verticals
