### ISSUE TITLE
Copper Tools Durability UI Glitch

### ISSUE THREAD

**Issue by ringprod** [CiFru/AdditionalBlocks#3]
**What's wrong with the mod**
When using copper tools, the durability will span across the entire screen over the rest of the items in the inventory.

**What Minecraft Version are you playing**
1.20.1 Fabric

**What version of the mod are you using**
2.1.1

**Comment by CiFru** [comment]
Thanks for reporting the bug. Will be patched in the next update.

**Comment by CiFru** [comment]
The update that's supposed to patch this bug has been released (Version 2.1.3). Please let me know if the bug persists.

**Comment by ringprod** [comment]
it works now thank you!
